site_name: Documentação CEMEPI - Dados

nav:
- Home: index.md
- Notebooks:
  - Template: notebooks/template_notebook.md
  - "Exemplo: Similaridade": notebooks/estudo-similaridade.md
- Módulos src:
  - Template: src/template_src.md
  - Scrapers:
    - Scraper TJSP fase capa: src/scrapers/scraper_tjsp_capa_request.md
- Scripts:
  - Template: scripts/template_script.md
  - Docs:
    - Pipeline Scraper TJSP fase capa: scripts/coleta_PGE_GPDR_tjsp_fase_capa.md
- Guias:
  - Configuração do ambiente: guias/configuracao_ambiente.md
  - Padrão de logging: guias/logging_padrao.md
